### ISSUE TITLE
Doc needs update for 71x0, Beagle. References from VIC -> JH need updated.

### ISSUE THREAD

**Issue by robertlipe** [starfive-tech/u-boot#11]
sft-riscv-uboot/arch/riscv/cpu/

https://github.com/starfive-tech/sft-riscv-uboot/tree/starfive/doc/board probably needs an entry for BeagleV

board/starfive/vic7100/vic7100.c and related code needs renamed from VIC to JH. (Two steps or one? Once for VIC->JH and another for 7100 to 7110 or do them at the same time?) Also: 7100 isn't a board, it's an arch, right? Beagle is a board that uses 7100 arch.

https://github.com/starfive-tech/sft-riscv-uboot/tree/starfive/doc/board needs entries for BeagleV. Remember that serial_starfive is like ns16550, but different.

Originally from: https://github.com/starfive-tech/sft-riscv-uboot/issues/6

**Comment by pdp7** [comment]
@tekkamanninja has now changed all the references.
