### ISSUE TITLE
make new default branch rebased on 2021.04

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/u-boot#13]
@tekkamanninja Right now there are two active branches:

* https://github.com/starfive-tech/u-boot/tree/Fedora_VIC_7100_2021.04
* https://github.com/starfive-tech/u-boot/tree/Fedora

`Fedora` is default so people are opening PR's against that, but it seems like `Fedora_VIC_7100_2021.04` is newer. Could you change the default branch to be based on 2021.04?

**Comment by pdp7** [comment]
@tekkamanninja  from @sarnold in Slack:
> make a new default branch cut from u-boot: commit b46dd116ce03e235f2a7d4843c6278e1da44b5e1 (tag: v2021.04) then we can do a PR for review

**Comment by sarnold** [comment]
I have a clean branch ready, but it needs a target branch.  Can you make a new branch from:

upstream u-boot: https://github.com/u-boot/u-boot/commit/b46dd116ce03e235f2a7d4843c6278e1da44b5e1 (tag: v2021.04)

**Comment by pdp7** [comment]
closing in favor of #15
