### ISSUE TITLE
earlycon=sbi is deprecated

### ISSUE THREAD

**Issue by xypron** [starfive-tech/u-boot#2]
Console output through SBI has been deprecated. Cf. https://github.com/riscv/riscv-sbi-doc/blob/master/riscv-sbi.adoc#4-legacy-extensions-eids-0x00---0x0f

LInux with CONFIG_SERIAL_8250_CONSOLE=y has a driver 8250_early.c which can be used for early output.

Hardcoding the command line in U-Boot is anyway a bad idea. Just supply a boot.scr file on the boot partition instead.

**Comment by xypron** [comment]
``
earlycon=uart,mmio32,0x12440000
```
seems to do the job.

**Comment by geertu** [comment]
Given the DTB seems to have a proper chosen/stdout-path, plain "earlycon" should work, too.

**Comment by davidlt** [comment]
Correct, "earlycon" is enough for the kernel to handle earlycon based on chosen node. SBI earlycon is legacy and to disabled once SBI v0.3 shows up.

**Comment by pdp7** [comment]
@xypron is this something you would be able to create a PR for?  Or is this something I should ask @MichaelZhuxx or @tekkamanninja to resolve?

**Comment by tekkamanninja** [comment]
Sure, I have tested, and I will also update Fedora Image , Great thanks to @xypron @davidlt @pdp7 @geertu
