### ISSUE TITLE
no serial number and ethaddr=ff:ff:ff:ff:ff:ff

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/u-boot#21]
I currently see this output in the output from `printenv`:
```
serial#=00000000
```
and
```
ethaddr=ff:ff:ff:ff:ff:ff
```
Is OTP driver in u-boot expected to work?

https://github.com/starfive-tech/u-boot/blob/494e5ef7b8071d0b2fba50616d97771e44cbcb7c/drivers/misc/starfive-otp.c#L213

https://github.com/starfive-tech/u-boot/blob/494e5ef7b8071d0b2fba50616d97771e44cbcb7c/drivers/misc/Kconfig#L78

https://github.com/starfive-tech/u-boot/blob/494e5ef7b8071d0b2fba50616d97771e44cbcb7c/configs/starfive_vic7100_beagle_v_smode_defconfig#L769

https://github.com/starfive-tech/u-boot/blob/Fedora_VIC_7100_2021.04/configs/starfive_vic7100_beagle_v_smode_defconfig#L769

@tekkamanninja @MichaelZhuxx could you please comment?

@atishp04 is asking me how this might be fixed.

@geertu has this been a problem for you when doing TFTP boot?

**Comment by pdp7** [comment]
TFTP works ok.

I switched to the beta board instead of earlier board and it does have MAC address in OTP:
```
ethaddr=2c:f7:f1:1b:e3:3f
```

**Comment by MichaelZhuxx** [comment]
@pdp7 otp function should be ok, here is commit https://github.com/starfive-tech/u-boot/commit/3f3ac01a29ad1cd5fa519d86f81daead2447f1d4, aslo attached enviroment variables from my beta board:
```
efi_dtb_prefixes=/ /dtb/ /dtb/current/
ethact=dwmac.10020000
ethaddr=2c:f7:f1:1b:e3:5f
fdt_addr=fffd1b90
fdt_addr_r=0x88000000
```
you can try to look up your MAC address https://dnschecker.org/mac-lookup.php, the manufactury ID should be Seeed Technology Inc.
