### ISSUE TITLE
Upstream u-boot support

### ISSUE THREAD

**Issue by kallisti5** [starfive-tech/u-boot#38]
I just received my StarFive VisionFive 2... however noticed it doesn't have support in upstream u-boot.

When will StarFive attempt to upstream their work here?

**Comment by kallisti5** [comment]
```
$ pwd
~/u-boot/configs
$ ls starfive*
ls: cannot access 'starfive*': No such file or directory
```

**Comment by davidlt** [comment]
StarFive started upstreaming processes for kernel, U-Boot and OpenSBI some weeks ago. The initial U-Boot patchset was posted on Dec 12, 2022: https://lists.denx.de/pipermail/u-boot/2022-December/501961.html

Note, that it will take weeks to months before things get properly reviewed and land in releases. We don't even have all DT bindings yet approved.

**Comment by kallisti5** [comment]
:+1:   As long as it's in progress i'm happy :laughing: 
I've seen too many arm boards where they don't even try to upstream stuff.  Thanks!!

**Comment by davidlt** [comment]
@kallisti5 You can follow upstreaming status here: https://rvspace.org/en/project/JH7110_Upstream_Plan

**Comment by colemickens** [comment]
That page does ... not list u-boot upstream status information.

**Comment by colemickens** [comment]
I do know that VF2 is in upstream u-boot, but the upstream docs don't list NVME support yet. And the stock VF2 published firmware doesn't implement distroboot or standard boot in a way that boots off the NVME normally, which is disappointing.
