### ISSUE TITLE
[FYI] bootloader, ddr init boot, u-boot and Recover bootloader

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/u-boot#5]
New page by @lakshanthad on the wiki:
 **[Update bootloader, ddr init boot, u-boot and Recover bootloader](https://wiki.seeedstudio.com/BeagleV-Update-bootloader-ddr-init-boot-uboot-Recover-bootloader/)**
> This wiki explains how to update the bootloader and ddr init boot on to the SPI flash of BeagleV™ - Starlight. On the other hand, it also explains how to recover the bootloader if you accidentally emptied the flash or if the flash is damaged on your BeagleV™ - StarLight.

For those with forum access, feedback is welcome here:
https://forum.beagleboard.org/t/update-bootloader-ddr-init-boot-u-boot-and-recover-bootloader/29558

**Comment by pdp7** [comment]
@trini @lbmeng @davidlt @tekkamanninja fyi

**Comment by trini** [comment]
@pdp7 Is there a reason it says to use SecureCRT for the debug port?  Also, what is the limit on the size of what can be loaded via this port?

**Comment by pdp7** [comment]
Let me check with the author @lakshanthad

**Comment by pdp7** [comment]
@trini I am pretty sure SecureCRT is just being used as an example of terminal emulator. I have used minicom to send secondBoot, ddrinit and uboot binaries over xmodem with no problems.  I need to document this and share that with @lakshanthad to get the guide updated

**Comment by pdp7** [comment]
@trini Regarding debug recovery, Lakshantha told me:
> I saw that some people asked about why I used SecureCRT for DEBUG header. That is because you cant successfully transfer the vic_second_boot.boot.bin using XMODEM on minicom on the DEBUG header. After you upload the file using minicom and type "do 0x18000000", there is no response. So for the time being, I have used SecureCRT which works.

Lakshantha will be back on May 6 but in the meantime it is possible for us to figure out a terminal emulator that will handle it correctly.  I feel like we can figure it out if we put our minds together.  No one wants to be using securecrt.

**Comment by tekkamanninja** [comment]
I have tried SecureCRT that worked, but that is the only app that can work with BootROM.

**Comment by yimingyiming** [comment]
Someone tell me "Minicom" can work with BootROM. You should install "lrzsz" package and the command binary is "/usr/bin/sx" to send file with Xmodem.

**Comment by pdp7** [comment]
FYI - @kprasadvnsi created a bootloader recovery tool is ready for testing and replaces the need to use SecureCRT for BootROM. Feel free to provide feedback.

https://github.com/kprasadvnsi/JH71xx-tools

**Comment by pdp7** [comment]
I am going to close this issue now that we have solutions for both the normal update method and the recovery method.
