### ISSUE TITLE
[JH7110] Fix CONFIG_VIDEO_PCI_DEFAULT_FB_SIZE in defconfig

### ISSUE THREAD

**Issue by ganboing** [starfive-tech/u-boot#50]
https://github.com/starfive-tech/u-boot/blob/ac0ac696256abf412826d74ee918dd417e207d7b/configs/starfive_visionfive2_defconfig#L134

This is wrong. If you are trying to reserve the framebuffer of size 4 * 3840 * 2160, then it should be 33177600 in decimal, not hexadecimal. 0x33177600 is ~817M!!

**Comment by MichaelZhuxx** [comment]
@ganboing thanks for your reminding, we will fixe in next-release;

**Comment by JamiKettunen** [comment]
@MichaelZhuxx Looks fixed since https://github.com/starfive-tech/u-boot/commit/23d50b953b09f0fa9efbcdfc000b64eafd7cf533 (v3.4.5), this can be closed
