### ISSUE TITLE
implement mechanism to reset PMIC

### ISSUE THREAD

**Issue by xypron** [starfive-tech/u-boot#8]
In the device-tree we have a node with compatible gpio-restart.

```
                gpiorst:gpio-restart {
                        compatible = "gpio-restart";
                        gpios = <&gpio 63 GPIO_ACTIVE_HIGH>;
                };
```

Why is CONFIG_SYSRESET_GPIO not selected to make use of it?

**Comment by jonathangray** [comment]
See https://github.com/starfive-tech/Fedora_on_StarFive/issues/25
Despite the device tree and code in the U-Boot and OpenSBI branches it appears that reset only works when talking to the PMIC over I2C or pushing the button next to the USB-C power which is connected to the PMIC.

**Comment by pdp7** [comment]
please see comment here from @MichaelZhuxx 
https://github.com/starfive-tech/Fedora_on_StarFive/issues/25#issuecomment-840228593

**Comment by xypron** [comment]
This issue was about U-Boot. It is good that we found out how to make a reset work in Linux.
But we also want the reset command in U-Boot to work. So we shoudn't close this issue.

The best solution would be to implement the reset in OpenSBI.

**Comment by pdp7** [comment]
@xypron thank you for pointing that out and re-opening

**Comment by MichaelZhuxx** [comment]
@pdp7 yes, that's my concern in todays weekly meeting, we need merge its same way(tell the pmic to reset the whole system) from linux to u-boot. @tekkamanninja please try to fix it. then I can offically release a u-boot binary. thanks.

**Comment by xypron** [comment]
@MichaelZhuxx 
The system reset should only be implemented once and that is in OpenSBI. U-Boot and Linux should call the system reset extension. This just like ARM does with PSCI.

**Comment by MichaelZhuxx** [comment]
@xypron good point. I think that's the best way. @tekkamanninja what's your opinion?

**Comment by MichaelZhuxx** [comment]
https://github.com/starfive-tech/opensbi/commit/b5facf907299c0bf263b30c92f17b79ccf2379da
yes, we have done same method in openSBI to enable the system reset by GPIO63. now we should implement it by I2C.

**Comment by pdp7** [comment]
> [starfive-tech/opensbi@b5facf9](https://github.com/starfive-tech/opensbi/commit/b5facf907299c0bf263b30c92f17b79ccf2379da)
> yes, we have done same method in openSBI to enable the system reset by GPIO63. now we should implement it by I2C.

Yes, the does seem ideal to implement restarting PMIC via I2C in OpenSBI so that SBI reset will work.

**Comment by pdp7** [comment]
refer to https://github.com/starfive-tech/opensbi/issues/5
